Update pubCrossRef.py
The httpResp.read() can sometimes broke down with the error message:
ssl.SSLError: ('The read operation timed out',)
and since I put this in the try / except module, I have to first create the jsonStr to avoid the UnboundLocalError
(↑ maybe this could be omit after I added the "return None",I didn't try it)